HOST = 'xxxx' # localhost
PORT = 3306
DATABASE = 'xxxx'
USERNAME = 'xxxx'
PASSWORD = 'xxxxx'

DB_URI = f"mysql+pymysql://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}?charset=utf8mb4"

SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = True

SECRET_KEY = 'XXXXXXXXXXXX'